# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dbConn, viewAll
from addNew import Ui_addNewWindow


class Ui_secondWindow(object):
    def setupUi(self, secondWindow):
        secondWindow.setObjectName("secondWindow")
        secondWindow.resize(531, 302)
        self.centralwidget = QtWidgets.QWidget(secondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 70, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.checkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.checkBtn.setGeometry(QtCore.QRect(90, 110, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBtn.setFont(font)
        self.checkBtn.setObjectName("checkBtn")
        self.viewAllBtn = QtWidgets.QPushButton(self.centralwidget)
        self.viewAllBtn.setGeometry(QtCore.QRect(90, 150, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.viewAllBtn.setFont(font)
        self.viewAllBtn.setObjectName("viewAllBtn")
        self.addMoreBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addMoreBtn.setGeometry(QtCore.QRect(90, 190, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addMoreBtn.setFont(font)
        self.addMoreBtn.setObjectName("addMoreBtn")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(283, 20, 221, 221))
        self.listWidget.setObjectName("listWidget")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(40, 220, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"text-align: justify;")
        self.errorLabel.setObjectName("errorLabel")
        secondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(secondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        secondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(secondWindow)
        self.statusbar.setObjectName("statusbar")
        secondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(secondWindow)
        QtCore.QMetaObject.connectSlotsByName(secondWindow)
        
        self.checkBtn.clicked.connect(self.viewInfo)
        self.addMoreBtn.clicked.connect(self.openAddNewWindow)
        self.viewAllBtn.clicked.connect(self.openViewAllInfo)

    def retranslateUi(self, secondWindow):
        _translate = QtCore.QCoreApplication.translate
        secondWindow.setWindowTitle(_translate("secondWindow", "MainWindow"))
        self.label.setText(_translate("secondWindow", "Enter website or view all passwords"))
        self.checkBtn.setText(_translate("secondWindow", "Check"))
        self.viewAllBtn.setText(_translate("secondWindow", "View All"))
        self.addMoreBtn.setText(_translate("secondWindow", "Add More"))
        self.errorLabel.setText(_translate("secondWindow", ""))

    def viewInfo(self):
        self.listWidget.clear()
        res = []
        websiteName = self.lineEdit.text()
        if websiteName == '':
            self.errorLabel.setText('You didn\'t enter a website')
        else:
            res = dbConn.getOneWebsiteInfo(websiteName)
            if websiteName in res:
                self.errorLabel.setText('')
                for i in range(len(res)):
                    self.listWidget.addItem(str(res[i]))
            elif websiteName not in res:
                self.errorLabel.setText('Website doesn\'t exist')

    def openAddNewWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_addNewWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openViewAllInfo(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = viewAll.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    secondWindow = QtWidgets.QMainWindow()
    ui = Ui_secondWindow()
    ui.setupUi(secondWindow)
    secondWindow.show()
    sys.exit(app.exec_())
